### ISSUE TITLE
URL entities are not displayed in Maltego

### ISSUE THREAD

**Issue by johnnykv** [allfro/canari#12]
When a canari transform returns a URL entity it seems that canari returns the correct XML:

``` xml
<MaltegoMessage>
 <MaltegoTransformResponseMessage>
  <Entities>
    <Entity Type="maltego.URL">
      <Value>http://woop.woop.org</Value>
      <Weight>1</Weight>
     </Entity>
    </Entities>
  </MaltegoTransformResponseMessage>
</MaltegoMessage>
```

But the URL entity is not rendered in Maltego.

This problem can be reproduced by following these steps:
1. `canari create-package dummy`
2. replace line 68 in helloworld.py  with `response += URL('http://woop.woop.org')`
3. `canari install-package dummy` (from src directory)
4. `python setup.py install` (from project root directory)
5. Test the transform on a Person entity

I have not been able to find the root cause myself - might be a problem in Maltego?

**Comment by lorenzoromani1983** [comment]
I am having the same problem with URLS. Please can you tell me how to upgrade?
I created my own local transform but doesn't show URLs.

thanks

**Comment by lorenzoromani1983** [comment]
P.S.: in debug the entity is visualized but does not get rendered:

Entity Type="maltego.URL">
Value>https://github.com/bokeh/bokeh/tree/master/examples/app/crossfilter</Value>
Weight>100</Weight>
/Entity>

the xml is therefore ok.
I am creating the entity like this:

 m.addEntity('maltego.URL', ''.join(link))
