### ISSUE TITLE
how do i request value from user through the dialog box?

### ISSUE THREAD

**Issue by vnoxygen** [allfro/canari#52]
I would like the user to specify the time variable for a search function on specific entity. This value would be dynamic according to the user's need. Another alternative is for the user to create a new properties inside the entity itself for the value, quite troublesome.

**Comment by allfro** [comment]
Hi @vnoxygen 

I would look at the easygui lib. This would be the only approach possible in canari for local transforms. For remote transforms, I would specify parameters in the transform config dialog. Easygui is packaged with Canari with a few hacks to get around some bugs on Mac OS X. Take a look at the easygui library docs here for more information: http://easygui.sourceforge.net/. The Canari version of easygui can be used by using `import canari.easygui as easygui`

**Comment by vnoxygen** [comment]
I was thinking of using this method. I think it is similar to "NetblockToNetblocks" transformation where you will specify how big the size split is? 

Do you have the code how to specify this input field inside Canari, and how to retrieve it from the request?

This might be the best option since it will be a remote transform.

**Comment by allfro** [comment]
That would be something you configure within the TDS. You don't do that
within Canari. The seed will instruct the client that the transform expects
a mandatory parameter. At that point, the client will prompt the user for
input. In your transform  code you can query parameters by looking at
what's inside `request.parameters`.

**Comment by vnoxygen** [comment]
I understand now. Thank you for your support allfro. For public reference, you could go to the transform settings through the URL: <domain>/iTDS/transformsettings.

At least it is clear that Canari does not set the Seed's transform settings.
